- name: perfecto-doc
  type: doc
  id: perfecto-doc-12451
  description: "this is a sample doc sync"
  sync: 
    enabled: true
    mode: local-agent
    agentType: py-quant-ai 
    sharedVolume: 
      path: /opt/     
    schedule: "0 0 * * *"
    source: 
    - type: git
      url: "https://github.com/argoproj/argo-cd.git"
      branch: main
      paths: ["/en/docs"]
      credentials: 
        type: secret
        name: name-secret-token  
    database: 
      type: mongo
      path:  
        serviceName: mongo-svc
	    # IF serviceName, endpoint is ignored, endpoint is more of an external database setup
        endpoint: 10.2.24.1:2121
        path: /hawk/doc/perfecto-doc/