apiVersion: v1
data:
  token: Z2l0aHViX3BhdF8xMUFVVU1FWlEwNDNOTXN2aVJWbG9YXzRIMGFoWXo4MEZSNG9SZDVYWklWcXBKaGxSaVo0aGxXMjJRb01SZ0FwT1dIQUJCUVhEV3VjQUtLY1ZLCg==
  username: aW1tbmFuCg==
kind: Secret
metadata:
  name: git-secret-token
  namespace: hawk
