apiVersion: batch/v1
kind: Job
metadata:
  name: any-dummy-job
spec:
  template:
    spec:
      containers:
      - name: dummy-container
        image: busybox:latest
        command: ["sh", "-c", "ls -l $HOME/Desktop/ && sleep 300"]
        env: 
        - name: SOURCE_RESULT
          value: |-
          {"name": "basic-git"}
        volumeMounts:
        - mountPath: "$HOME/Desktop/"
          name: hawk-shared-volume
    volumes:
      - name: hawk-shared-volume
        persistentVolumeClaim:
          claimName: hawk-shared-pvc 
  backoffLimit: 10